apiVersion: v2
name: frontend
description: Frontend of storage-utils extension.
type: application
version: 1.0.0
appVersion: "1.0.0"
home: https://github.com/kubesphere-extensions/kse-extensions
sources:
  - https://github.com/kubesphere-extensions/kse-extensions
