name: BuildExtensionsMuseum

on:
  workflow_dispatch: # Manual trigger
  workflow_run:
    workflows:
      - BuildExtensionsCharts
    types:
      - completed
  push:
    tags:
      - 'v*'
    branches:
      - "main"

jobs:
  build-multiarch:
    runs-on: ubuntu-latest
    if: github.repository == 'kubesphere-extensions/ks-extensions'
    steps:
      - name: Prepare
        id: prepare
        run: |
          VERSION=latest

          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          fi
          echo "version=${VERSION}" >> "$GITHUB_OUTPUT"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: filter helm charts
        run: |
          if [[ ${GITHUB_REF#refs/*/} =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              for file in .extensions-museum/*.tgz; do
                if [[ ! $file =~ -[0-9]+\.[0-9]+\.[0-9]+\.tgz$ ]]; then
                  rm "$file"
                fi
              done
          fi

      - name: Login to Aliyun
        uses: docker/login-action@v3
        with:
          registry: registry.cn-beijing.aliyuncs.com
          username: ${{ secrets.ALIYUNCS_USERNAME }}
          password: ${{ secrets.ALIYUNCS_PASSWORD }}

      - name: Login to DOCKER
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push ks-extensions-museum images
        uses: docker/build-push-action@v6
        with:
          context: ${{ github.workspace }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
              docker.io/kubesphere/ks-extensions-museum:${{ steps.prepare.outputs.version }}
              registry.cn-beijing.aliyuncs.com/kubesphereio/ks-extensions-museum:${{ steps.prepare.outputs.version }}

      - name: Login to HUAWEICLOUD
        uses: docker/login-action@v3
        with:
          registry: swr.cn-southwest-2.myhuaweicloud.com
          username: ${{ secrets.HUAWEICLOUD_USERNAME }}
          password: ${{ secrets.HUAWEICLOUD_PASSWORD }}

      - name: Sync extension museum to HUAWEICLOUD
        run: |
          docker pull docker.io/kubesphere/ks-extensions-museum:${{ steps.prepare.outputs.version }}
          docker tag docker.io/kubesphere/ks-extensions-museum:${{ steps.prepare.outputs.version }} swr.cn-southwest-2.myhuaweicloud.com/ks/kubesphere/ks-extensions-museum:${{ steps.prepare.outputs.version }}
          docker push swr.cn-southwest-2.myhuaweicloud.com/ks/kubesphere/ks-extensions-museum:${{ steps.prepare.outputs.version }}
