name: BuildExtensionsCharts

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.extensions-museum/**'
      - '.github'

jobs:
  build-charts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Package latest charts
        run: |
          ARCH=$(uname -m)
          if [ "$ARCH" == "x86_64" ]; then
            ARCH="amd64"
          elif [ "$ARCH" == "aarch64" ]; then
            ARCH="arm64"
          fi
          LATEST_RELEASE=$(curl -sH "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/kubesphere/ksbuilder/releases/latest" | jq -r '.tag_name')
          KSBUILDER_VERSION=$LATEST_RELEASE;ARCH=$ARCH make package-all-charts

      - name: Commit changes
        id: commit_step
        run: |
          git config --local user.email "ci-bot@kubesphere.io"
          git config --local user.name "ks-ci-bot"
          git add .extensions-museum
          if git diff --cached --quiet; then
            echo "No changes to commit"
            echo "has_changes=false" >> $GITHUB_ENV
          else
            git commit -m "sync charts by action" -s
            echo "has_changes=true" >> $GITHUB_ENV

            git push origin
          fi
          
